meshConfig:
  accessLogFile: /dev/stdout
  accessLogEncoding: JSON
  enableTracing: true
  # ────────────────────────────────────────────────────
  # turn on the new (v2) tracing configuration schema
  defaultConfig:
    proxyMetadata:
      # this is for supporting for "missing selected ALPN property" error
      GRPC_ENFORCE_ALPN_ENABLED: "false"
  defaultProviders:
    accessLogging:
      - otel-als                    # ← ここが正解。「v2 Telemetry」では defaultProviders に書く
    metrics:
      - prometheus                  # Istio が Prometheus 形式でメトリクスを吐く
    tracing:
      - otel                         # OTLP トレースを送る場合はここにプロバイダー名を列挙

  # ────────────────────────────────────────────────────
  # wire up your OTLP‐based extensionProvider for Istio’s mesh
  # Doc: https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider
  extensionProviders:
    # - name: otel-tracing
    #   opentelemetry:
    #     port: 4317
    #     service: otel-collector.observability.svc.cluster.local
    #     resource_detectors:
    #       environment: {}
    - name: otel-als
      envoyOtelAls:
        service: otel-collector.observability.svc.cluster.local
        port: 4317
        logFormat:
          labels:
            pod: "%ENVIRONMENT(POD_NAME)%"
            namespace: "%ENVIRONMENT(POD_NAMESPACE)%"
            cluster: "%ENVIRONMENT(ISTIO_META_CLUSTER_ID)%"
            mesh: "%ENVIRONMENT(ISTIO_META_MESH_ID)%"
    # - name: otel
    #   envoyOtelAls:
    #     service: opentelemetry-collector.istio-system.svc.cluster.local
    #     port: 4317
    #     logFormat:
    #       labels:
    #         pod: "%ENVIRONMENT(POD_NAME)%"
    #         namespace: "%ENVIRONMENT(POD_NAMESPACE)%"
    #         cluster: "%ENVIRONMENT(ISTIO_META_CLUSTER_ID)%"
    #         mesh: "%ENVIRONMENT(ISTIO_META_MESH_ID)%"
      