data:
  config.yaml: |
    external_services:
      custom_dashboards:
        enabled: true
      istio:
        root_namespace: istio-system
      prometheus:
        url: "http://prometheus.istio-system:9090/"
      tracing:
        enabled: true
        internal_url: "http://tracing.istio-system:16685/jaeger"
        use_grpc: true
        external_url: "http://localhost:16686/jaeger"
      grafana:
        enabled: true
        internal_url: 'http://grafana.telemetry:3000/'
        external_url: 'http://localhost:3000/grafana'
    server:
      observability:
        metrics:
          enabled: true
          port: 9090
      port: 20001
      web_root: /kialikind: ConfigMap
kind: ConfigMap
